// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUEm0o8NH5cwzkwiasaMsGOhIdIuVqhRI',
    appId: '1:537634283817:web:607f593a332433f7049738',
    messagingSenderId: '537634283817',
    projectId: 'p-cube-plus',
    authDomain: 'p-cube-plus.firebaseapp.com',
    storageBucket: 'p-cube-plus.firebasestorage.app',
    measurementId: 'G-6DWG7127XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlKi3tEh58dR7BcjPdXNHdb83bS2OS35E',
    appId: '1:537634283817:android:fee1127f13e7e27e049738',
    messagingSenderId: '537634283817',
    projectId: 'p-cube-plus',
    storageBucket: 'p-cube-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuEq4jAaPoatZ9XceDGMUWMil7tcP70Bw',
    appId: '1:537634283817:ios:82ea81be606567e5049738',
    messagingSenderId: '537634283817',
    projectId: 'p-cube-plus',
    storageBucket: 'p-cube-plus.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuEq4jAaPoatZ9XceDGMUWMil7tcP70Bw',
    appId: '1:537634283817:ios:82ea81be606567e5049738',
    messagingSenderId: '537634283817',
    projectId: 'p-cube-plus',
    storageBucket: 'p-cube-plus.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUEm0o8NH5cwzkwiasaMsGOhIdIuVqhRI',
    appId: '1:537634283817:web:a1f33e7f2b021864049738',
    messagingSenderId: '537634283817',
    projectId: 'p-cube-plus',
    authDomain: 'p-cube-plus.firebaseapp.com',
    storageBucket: 'p-cube-plus.firebasestorage.app',
    measurementId: 'G-CM0W00K9KN',
  );

}