name: presentation
publish_to: 'none'

environment:
  sdk: ">=3.0.0"

dev_dependencies:
  flutter_lints: ^5.0.0

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../domain

  get_it: ^8.0.2
  meta: ^1.15.0

  provider: ^6.1.2
  lottie: ^3.1.3
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.0

  ibeacon_plugin:
    git: https://github.com/p-cube-plus/ibeacon_plugin.git

# flutter pub run build_runner watch --delete-conflicting-outputs