name: presentation
publish_to: 'none'

environment:
  sdk: ">=3.0.0"

dev_dependencies:
  flutter_lints: ^4.0.0

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../domain

  get_it: ^7.6.7
  lottie: ^2.7.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  provider: ^6.1.2

# flutter pub run build_runner watch --delete-conflicting-outputs