name: presentation
publish_to: 'none'

environment:
  sdk: ">=3.0.0"

dev_dependencies:
  flutter_lints: ^5.0.0

dependencies:
  get_it: ^8.0.2
  flutter:
    sdk: flutter
  domain:
    path: ../domain

  # 위젯 상태관리
  provider: ^6.1.2

  # 로티 실행 (스플래시 애니메이션)
  lottie: ^3.1.3
  # SVG 리소스 읽기
  flutter_svg: ^2.0.10+1

  # 네이티브 토스트바
  fluttertoast: ^8.2.5

  # 런타임 권한 처리
  permission_handler: ^11.3.1

  # 알림 처리
  flutter_local_notifications: ^18.0.1
  # FCM
  firebase_messaging: ^15.1.0 

  # 웹뷰
  webview_flutter: ^4.10.0
  # 앱링크
  url_launcher: ^6.3.1  

  # 비콘 스캐너
  ibeacon_plugin:
    git: https://github.com/p-cube-plus/ibeacon_plugin.git

  # 이미지 선택
  image_picker: ^1.1.2
  # 바코드 분석
  google_mlkit_barcode_scanning: ^0.13.0
  