name: app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# flutter create --template=package [만들고자하는 패키지명]
dependencies:
  flutter:
    sdk: flutter
  presentation:
    path: ../presentation
  data:
    path: ../data

  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.3.7
  
# 앱 아이콘
# 이미지 설정 후 아래 명령어 사용
# flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/symbol.png"
  min_ask_android: 21

# 앱 시작 시 로딩 화면
# 설정 후 아래 명령어 사용
# flutter pub run flutter_native_splash:remove
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/symbol.png"

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/images/icons/
     - assets/lottie/
  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/font/SpoqaHanSansNeo-Thin.ttf
          weight: 100
        - asset: assets/font/SpoqaHanSansNeo-Light.ttf
          weight: 300
        - asset: assets/font/SpoqaHanSansNeo-Regular.ttf
          weight: 400
        - asset: assets/font/SpoqaHanSansNeo-Medium.ttf
          weight: 500
        - asset: assets/font/SpoqaHanSansNeo-Bold.ttf
          weight: 700

# target SDK 변경
# android local.properties

# 앱 이름 변경 (pcube+)
# android:label=
# <key>CFBundleDisplayName</key>

# flutter channel stable
# flutter update --force

# flutter downgrade v3.22.3

# cd [flutter SDK 위치]
# git fetch
# git checkout 3.22.3
# flutter pub get



# flutter config --jdk-dir "JDK 설치 경로"
# https://stackoverflow.com/questions/79067849/flutter-3-24-3-problem-with-android-studio-ladybug-2024-2-1